name: Deploy to EC2

on:
  push:
    branches:
      - master  # Change to your branch if needed

jobs:
  deploy:
    runs-on: self-hosted  # Assumes you've set up a GitHub runner on EC2

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Pull latest changes on EC2
        run: |
          cd ~/projects/service2  # Adjust to your project path
          git pull

      - name: Install Dependencies
        run: |
          cd ~/projects/service2
          npm install  # Change as needed (yarn, pnpm, etc.)
      
      - name: Debug Node Path and User
        run: |
          which node
          whoami
          env

      - name: Restart Node Service
        run: |
         # pkill -f "node /home/ec2-user/projects/service2/server.js" || true  # Stop existing process (if any)
         # node /home/ec2-user/projects/service2/server.js
          nohup setsid node /home/ec2-user/projects/service2/server.js > /home/ec2-user/projects/service2/output.log 2>&1 &  disown
